<? $container = $this->navigation()->breadcrumbs(); /** @var $container \Zend\View\Helper\Navigation\Breadcrumbs */ ?>
<ol class="breadcrumb">
    <? foreach ($this->pages as $page):  /** @var Zend\Navigation\Page\AbstractPage $page */ ?>
        <? if (! $page->isActive()): ?>
            <li>
                <a href="<?=$page->getHref()?>">
                    <i class="<?=$page->get('ico')?>"></i>
                    <?=$page->getLabel()?>
                </a>
            </li>
        <? else: ?>
            <li class="active">
                <? if($container->getLinkLast()): ?> <a href="<?=$page->getHref()?>"> <? endif; ?>
                    <i class="<?=$page->get('ico')?>"></i>
                    <?=$page->getLabel()?>
                <? if($container->getLinkLast()): ?> </a> <? endif; ?>
            </li>
        <? endif; ?>
    <? endforeach;?>
</ol>