<ul class="nav navbar-nav">
    <? foreach ($this->container as $page):  /** @var Zend\Navigation\Page\AbstractPage $page */ ?>
        <li <?= $page->isActive() ? 'class="active"' : '' ?> >
            <a href="<?= $page->getHref() ?>">
                <i class="fa <?=$page->get('ico')?> margin-r-5"></i>
                <?= $page->getLabel() ?>
            </a>
        </li>
    <? endforeach; ?>
</ul>