version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
      - "443:443"
    volumes:
      - .:/var/www/salao
      - ./docker/nginx/site:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/usr/local/nginx/ssl
    links:
      - php-fpm

  php-fpm:
    build: .
    working_dir: /var/www/salao
    #command: composer doctrine-migrate
    environment:
        - DEBUG=1
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_USER=root
        - DB_PASS=root
        - DB_NAME=agenda
    volumes:
      - .:/var/www/salao
    links:
      - redis
      - mysql

  mysql:
    image: mysql:latest
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=agenda
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine