<? use \Site\Form\CadastroForm; ?>
<? /** @var CadastroForm $form */ ?>

<div class="register-box">
    <div class="register-box-body">
        <p class="login-box-msg">Registre-se</p>
        <? $form->prepare(); ?>
        <?= $this->form()->openTag($form) ?>
            <!-- NOME DO SALÃO -->
            <div class="form-group has-feedback <?= $form->getMessages(CadastroForm::NOME_SALAO) ? 'has-error' : '' ?>">
                <?= $this->formInput($form->get(CadastroForm::NOME_SALAO)->setAttribute('class', 'form-control')) ?>
                <span class="glyphicon glyphicon-asterisk form-control-feedback"></span>
                <?=$this->formElementErrors($form->get(CadastroForm::NOME_SALAO))?>
            </div>

            <!-- TELEFONE DO SALÃO -->
            <div class="form-group has-feedback <?= $form->getMessages(CadastroForm::TELEFONE_SALAO) ? 'has-error' : '' ?>">
                <?= $this->formInput($form->get(CadastroForm::TELEFONE_SALAO)->setAttribute('class', 'form-control')) ?>
                <span class="glyphicon glyphicon-phone-alt form-control-feedback"></span>
                <?=$this->formElementErrors($form->get(CadastroForm::TELEFONE_SALAO))?>
            </div>

            <!-- RESPONSÁVEL PELO SALÃO -->
            <div class="form-group has-feedback <?= $form->getMessages(CadastroForm::NOME_ADMINISTRADOR_SALAO) ? 'has-error' : '' ?>">
                <?= $this->formInput($form->get(CadastroForm::NOME_ADMINISTRADOR_SALAO)->setAttribute('class', 'form-control')) ?>
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
                <?=$this->formElementErrors($form->get(CadastroForm::NOME_ADMINISTRADOR_SALAO))?>
            </div>

            <!-- EMAIL RESPONSÁVEL PELO SALÃO -->
            <div class="form-group has-feedback <?= $form->getMessages(CadastroForm::EMAIL_ADMINISTRADOR_SALAO) ? 'has-error' : '' ?>">
                <?= $this->formInput($form->get(CadastroForm::EMAIL_ADMINISTRADOR_SALAO)->setAttribute('class', 'form-control')) ?>
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                <?=$this->formElementErrors($form->get(CadastroForm::EMAIL_ADMINISTRADOR_SALAO))?>
            </div>

            <!-- SENHA RESPONSÁVEL PELO SALÃO -->
            <div class="form-group has-feedback <?= $form->getMessages(CadastroForm::SENHA_ADMINISTRADOR_SALAO) ? 'has-error' : '' ?>">
                <?= $this->formInput($form->get(CadastroForm::SENHA_ADMINISTRADOR_SALAO)->setAttribute('class', 'form-control')) ?>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                <?=$this->formElementErrors($form->get(CadastroForm::SENHA_ADMINISTRADOR_SALAO))?>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Registrar</button>
                </div>
            </div>
        <?= $this->form()->closeTag($form) ?>
        <a href="<?=$this->url('site-login')?>" class="text-center">Eu já tenho um registro</a>
    </div>
</div>