<? use \Salao\Form\ServicoForm; /** @var ServicoForm $form */ ?>
<? $this->layout()->header = 'Serviços do Salao' ?>
<!-- Main content -->
<section class="content">
    <div class="box box-primary">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <?=$this->partial('form-partial')?>
                </div>
            </div>
        </div>
    </div>
</section>


