<? $this->layout()->header = 'Serviços do Salao' ?>

<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <a class="btn btn-primary" data-toggle="modal" ><i class="fa fa-fw fa-plus-circle"></i>Novo Serviço</a>
        </div>

        <div class="box-body">
            <table class="table table-condensed" ng-show="servicos.length > 0">
                <tr>
                    <th>Serviço</th>
                    <th>Duração</th>
                    <th>Valor (R$)</th>
                    <th></th>
                </tr>
                <? function m2h($mins) {
                    // Se os minutos estiverem negativos
                    if ($mins < 0)
                        $min = abs($mins);
                    else
                        $min = $mins;

                    // Arredonda a hora
                    $h = floor($min / 60);
                    $m = ($min - ($h * 60)) / 100;
                    $horas = $h + $m;

                    // Matemática da quinta série
                    // Detalhe: Aqui também pode se usar o abs()
                    if ($mins < 0)
                        $horas *= -1;

                    // Separa a hora dos minutos
                    $sep = explode('.', $horas);
                    $h = $sep[0];
                    if (empty($sep[1]))
                        $sep[1] = 00;

                    $m = $sep[1];

                    // Aqui um pequeno artifício pra colocar um zero no final
                    if (strlen($m) < 2)
                        $m = $m . 0;

                    return sprintf('%02d:%02d', $h, $m);
                }  ?>
                <? /** @var \Salao\Entity\Servico $servico */ ?>
                <? foreach ($this->servicos as $servico): ?>
                    <tr>
                        <td><?=$servico->getDescricao()?></td>
                        <td><?=m2h($servico->getDuracao())?></td>
                        <td><?=$servico->getValor()?></td>
                        <td>
                            <a data-toggle="modal" ng-click="editar(servico)" ><i class="fa fa-fw fa-edit"></i></a>
                            <a data-toggle="modal" ng-click="confirmExcluir(servico)"><i class="fa fa-fw fa-trash"></i></a>
                        </td>
                    </tr>
                <? endforeach; ?>
            </table>
            <div ng-show="servicos.length > 0">
                <ul uib-pagination total-items="totalItems" ng-model="currentPage" items-per-page="itemsPerPage" max-size="maxSize" ng-change="pageChanged()"></ul>
            </div>

            <div class="fade modal" id="modal-servico">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title" id="modal-servico-title">Serviço</h4>
                        </div>
                        <div class="modal-body">
                            <form class="form-horizontal" role="form" name="servicoForm">
                                <div class="form-group" ng-class="{'has-error': (servicoForm.descricao.$invalid && servicoForm.descricao.$dirty)}" >
                                    <div class="col-sm-3">
                                        <label class="control-label">Serviço</label>
                                    </div>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" placeholder="Nome do serviço" name="descricao" ng-model="servico.descricao" ng-required="true" ng-minlength="5">
                                        <div ng-messages="servicoForm.descricao.$error" ng-show="servicoForm.descricao.$dirty">
                                            <div ng-message="required" class="help-block">
                                                Por favor, preencher o campo descrição
                                            </div>
                                            <div ng-message="minlength" class="help-block">
                                                O campo descrição deve ter no mínimo 5 caracteres
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group" ng-class="{'has-error': (servicoForm.duracao.$invalid && servicoForm.duracao.$dirty)}">
                                    <div class="col-sm-3">
                                        <label class="control-label">Duração</label>
                                    </div>
                                    <div class="col-sm-3">
                                        <input type="number" class="form-control" name="duracao" ng-model="servico.duracao" ng-required="true" min="0">
                                    </div>
                                    <div class="col-sm-6">
                                        <label class="control-label left">{{servico.duracao | minutesToHours}}</label>
                                    </div>
                                    <div ng-messages="servicoForm.duracao.$error" ng-show="servicoForm.duracao.$dirty" class="col-sm-9 col-lg-offset-3">
                                        <div ng-message="required" class="help-block">
                                            Por favor, preencher o campo duração
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group" ng-class="{'has-error': (servicoForm.valor.$invalid && servicoForm.valor.$dirty)}">
                                    <div class="col-sm-3">
                                        <label class="control-label">Valor (R$)</label>
                                    </div>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" placeholder="Valor em Reais" name="valor" ng-model="servico.valor" ng-currency currency-symbol="" ng-required="true">
                                        <div ng-messages="servicoForm.valor.$error" ng-show="servicoForm.valor.$dirty">
                                            <div ng-message="required" class="help-block">
                                                Por favor, preencher o campo valor.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            <button type="button" class="btn btn-primary" ng-hide="!servico.id" ng-click="atualizar(servico)" ng-disabled="servicoForm.$invalid" >Atualizar</button>
                            <button type="button" class="btn btn-primary" ng-hide="servico.id" ng-click="salvar(servico)" ng-disabled="servicoForm.$invalid" >Salvar</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="fade modal" id="excluir-servico">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title" id="excluir-servico-title">Excluir Serviço</h4>
                        </div>
                        <div class="modal-body">
                            <p>Deseja excluir este serviço ?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            <button type="button" class="btn btn-primary" ng-click="excluir(servico)">Sim</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>