<? $this->layout()->header = 'Serviços' ?>

<section class="content">
    <div class="box box-primary">
        <div class="box-body">
            <div class="box-header">
                <a class="btn btn-primary btn-box-tool" href="<?=$this->url(\Salao\Controller\ServicoController::ROUTE_NAME, ['action' => 'criar'])?>">
                    <i class="fa fa-fw fa-plus-circle"></i>
                </a>

                <div class="box-tools">
                    <div class="input-group input-group-sm" style="width: 400px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-responsive">
                <tr>
                    <th>Serviço</th>
                    <th>Duração</th>
                    <th>Valor (R$)</th>
                    <th></th>
                </tr>
                <? /** @var \Salao\Entity\Servico $servico */ ?>
                <? foreach ($this->servicos as $servico): ?>
                    <tr>
                        <td><?=$servico->getDescricao()?></td>
                        <td><?=$this->convertMinutesToHour($servico->getDuracao())?></td>
                        <td><?=$this->currencyFormat($servico->getValor())?></td>
                        <td class="text-right">
                            <a class="btn btn-primary btn-sm" aria-label="Settings" href="<?=$this->url(\Salao\Controller\ServicoController::ROUTE_NAME, ['action' => 'editar', 'id' => $servico->getId()])?>" ><i class="fa fa-fw fa-edit"></i></a>
                            <a class="btn btn-danger btn-sm" aria-label="Settings" href="<?=$this->url(\Salao\Controller\ServicoController::ROUTE_NAME, ['action' => 'excluir', 'id' => $servico->getId()])?>"><i class="fa fa-fw fa-trash danger"></i></a>
                        </td>
                    </tr>
                <? endforeach; ?>
            </table>

            <div ng-show="servicos.length > 0">
                <ul uib-pagination total-items="totalItems" ng-model="currentPage" items-per-page="itemsPerPage" max-size="maxSize" ng-change="pageChanged()"></ul>
            </div>
        </div>
    </div>
</section>