<? $this->layout()->header = 'Serviços do Salao' ?>

<section class="content">
    <div class="box box-primary">
        <div class="box-header with-border">
            <a class="btn btn-primary" href="<?=$this->url(\Salao\Controller\ServicoController::ROUTE_NAME, ['action' => 'criar'])?>"><i class="fa fa-fw fa-plus-circle"></i>Novo Serviço</a>
        </div>

        <div class="box-body">
            <table class="table table-condensed">
                <tr>
                    <th>Serviço</th>
                    <th>Duração</th>
                    <th>Valor (R$)</th>
                    <th></th>
                </tr>
                <? /** @var \Salao\Entity\Servico $servico */ ?>
                <? foreach ($this->servicos as $servico): ?>
                    <tr>
                        <td><?=$servico->getDescricao()?></td>
                        <td><?=$this->convertMinutesToHour($servico->getDuracao())?></td>
                        <td><?=$this->currencyFormat($servico->getValor())?></td>
                        <td class="text-right">
                            <a href="<?=$this->url(\Salao\Controller\ServicoController::ROUTE_NAME, ['action' => 'editar', 'id' => $servico->getId()])?>" ><i class="fa fa-fw fa-edit"></i></a>
                            <a data-toggle="modal" ng-click="confirmExcluir(servico)"><i class="fa fa-fw fa-trash"></i></a>
                        </td>
                    </tr>
                <? endforeach; ?>
            </table>

            <div ng-show="servicos.length > 0">
                <ul uib-pagination total-items="totalItems" ng-model="currentPage" items-per-page="itemsPerPage" max-size="maxSize" ng-change="pageChanged()"></ul>
            </div>

            <div class="fade modal" id="excluir-servico">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title" id="excluir-servico-title">Excluir Serviço</h4>
                        </div>
                        <div class="modal-body">
                            <p>Deseja excluir este serviço ?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            <button type="button" class="btn btn-primary" ng-click="excluir(servico)">Sim</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>