<? use \Salao\Form\SalaoForm; ?>
<? /** @var SalaoForm $form */ ?>
<? $this->layout()->header = 'Cadastro do Salao' ?>
<!-- Main content -->
<section class="content">
    <div class="box box-primary">
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" id="form-excluir-imagem" action="<?= $this->url(\Salao\Controller\CadastroController::ROUTE_NAME, ['action' => 'delete-image'])?>">
                        <div class="form-group">
                            <div class="col-sm-2"></div>
                            <div class="col-sm-9">
                                <img class="profile-user-img img-responsive img-circle" src="<?=$this->image?>" alt="Imagen do Salão">
                                <br/>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <? $form->setAttribute('class', 'form-horizontal'); ?>
                    <? $form->prepare(); ?>
                    <?= $this->form()->openTag($form) ?>
                    <? $image = $form->get(SalaoForm::IMAGE)->setAttribute('class', 'form-control');?>
                    <div class="form-group <?= $form->getMessages(SalaoForm::IMAGE) ? 'has-error' : '' ?>">
                        <label for="<?=SalaoForm::IMAGE?>" class="col-sm-2 control-label">Imagen</label>
                        <div class="col-sm-9">
                            <div class="input-group">
                                <?= $this->formFile($image) ?>
                                <span class="input-group-btn">
                                          <span class="btn btn-primary" id="excluir-imagem">Excluir Imagem</span>
                                        </span>
                            </div>
                            <?=$this->formElementErrors($image)?>
                        </div>
                    </div>

                    <div class="form-group <?= $form->getMessages(SalaoForm::NOME) ? 'has-error' : '' ?>">
                        <label for="<?=SalaoForm::NOME?>" class="col-sm-2 control-label">Nome</label>
                        <div class="col-sm-9">
                            <? $nome = $form->get(SalaoForm::NOME)->setAttribute('class', 'form-control'); ?>
                            <?= $this->formInput($nome) ?>
                            <?=$this->formElementErrors($nome)?>
                        </div>
                    </div>
                    <div class="form-group <?= $form->getMessages(SalaoForm::DIAS_FUNCIONAMENTO) ? 'has-error' : '' ?>">
                        <label class="col-sm-2 control-label">Dias de funcionamento</label>
                        <div class="col-sm-9">
                            <? $diasDeFuncionamento = $form->get(SalaoForm::DIAS_FUNCIONAMENTO)->setLabelAttributes(['class' => 'checkbox-inline']) ?>
                            <?= $this->formMultiCheckbox($diasDeFuncionamento) ?>
                            <?=$this->formElementErrors($diasDeFuncionamento)?>
                        </div>
                    </div>
                    <div class="form-group <?= ($form->getMessages(SalaoForm::HORARIO_INICIO) || $form->getMessages(SalaoForm::HORARIO_INICIO)) ? 'has-error' : '' ?>"">
                    <label for="horario-inicio" class="col-sm-2 control-label">Horário</label>
                    <div class="col-sm-10">
                        <? $horarioInicio = $form->get(SalaoForm::HORARIO_INICIO)->setAttribute('class', 'form-control')->setAttribute('style', 'width: 100px; display: inline;'); ?>
                        <?= $this->formTime($horarioInicio) ?>
                        Até
                        <? $horarioFim = $form->get(SalaoForm::HORARIO_FIM)->setAttribute('class', 'form-control')->setAttribute('style', 'width: 100px; display: inline;'); ?>
                        <?= $this->formTime($horarioFim) ?>

                        <?=$this->formElementErrors($horarioInicio)?>
                        <?=$this->formElementErrors($horarioFim)?>
                    </div>
                </div>
                <div class="form-group <?= $form->getMessages(SalaoForm::TELEFONE) ? 'has-error' : '' ?>">
                    <label for="<?=SalaoForm::TELEFONE?>" class="col-sm-2 control-label" >Telefone fixo</label>
                    <div class="col-sm-2">
                        <? $telefone = $form->get(SalaoForm::TELEFONE)->setAttribute('class', 'form-control mask-phone') ?>
                        <?=$this->formInput($telefone) ?>
                        <?=$this->formElementErrors($telefone)?>
                    </div>
                </div>
                <div class="form-group <?= $form->getMessages(SalaoForm::CELULAR) ? 'has-error' : '' ?>">
                    <label for="<?=SalaoForm::CELULAR?>" class="col-sm-2 control-label">Telefone celular </label>
                    <div class="col-sm-2">
                        <? $celular = $form->get(SalaoForm::CELULAR)->setAttribute('class', 'form-control mask-phone') ?>
                        <?=$this->formInput($celular) ?>
                        <?=$this->formElementErrors($celular)?>
                    </div>
                </div>

                <div class="form-group <?= $form->getMessages(SalaoForm::ENDERECO) ? 'has-error' : '' ?>">
                    <label for="<?=SalaoForm::ENDERECO?>" class="col-sm-2 control-label">Endereço</label>
                    <div class="col-sm-9">
                        <div class="input-group">
                            <? $endereco = $form->get(SalaoForm::ENDERECO)->setAttribute('class', 'form-control'); ?>
                            <?=$this->formInput($endereco) ?>
                            <span class="input-group-btn">
                                          <button type="button" id="mostrar-no-mapa" class="btn btn-primary">Mostrar no mapa</button>
                                        </span>
                        </div>
                        <?=$this->formInput($form->get(SalaoForm::LAT)) ?>
                        <?=$this->formInput($form->get(SalaoForm::LNG)) ?>
                        <?=$this->formElementErrors($endereco)?>
                        <br>
                        <div id="mapa" style="height: 250px; width: 100%"></div>
                    </div>
                </div>

                <div class="form-group <?= $form->getMessages(SalaoForm::VISIVAL_NO_APP) ? 'has-error' : '' ?>">
                    <label for="<?=SalaoForm::VISIVAL_NO_APP?>" class="col-sm-2 control-label">Visível no APP</label>
                    <div class="col-sm-9">
                        <? $visivalNoApp = $form->get(SalaoForm::VISIVAL_NO_APP) ?>
                        <?=$this->formCheckbox($visivalNoApp) ?>
                        <?=$this->formElementErrors($visivalNoApp)?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-9">
                        <button type="submit" class="btn btn-primary" >Salvar</button>
                    </div>
                </div>
                <?= $this->form()->closeTag($form) ?>
            </div>
        </div>
    </div>
</section>
<?$this->inlineScript()
    ->appendFile('http://maps.googleapis.com/maps/api/js?key=AIzaSyAZVrwadhJEzcuUX3lOC63T9Ymplx8xpGU')
    ->appendFile($this->basePath('js/salao-endereco.js'))
?>
<?$this->headLink()
    ->appendStylesheet($this->basePath('css/salao-endereco.css'))
?>


