<?= $this->doctype() ?>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('application/img/favicon.ico')])
        ->prependStylesheet($this->basePath('vendor/admin-lte/bootstrap/css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('vendor/admin-lte/bootstrap/css/bootstrap.min.css'))

        ->prependStylesheet($this->basePath('vendor/admin-lte/dist/css/AdminLTE.min.css'))
        ->prependStylesheet($this->basePath('vendor/admin-lte/dist/css/skins/_all-skins.min.css'))
        ->prependStylesheet($this->basePath('vendor/admin-lte/dist/css/AdminLTE.min.css'))
        ->prependStylesheet($this->basePath('vendor/font-awesome/css/font-awesome.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->appendFile($this->basePath('vendor/admin-lte/plugins/jQuery/jquery-2.2.3.min.js'))
        ->appendFile($this->basePath('vendor/admin-lte/bootstrap/js/bootstrap.min.js'))
        ->appendFile($this->basePath('vendor/admin-lte/plugins/input-mask/jquery.inputmask.js'))
        ->appendFile($this->basePath('vendor/admin-lte/plugins/input-mask/jquery.inputmask.extensions.js'))
        ->appendScript('
            $(function () {
                var AdminLTEOptions = {
                };
            });'
        )
        ->appendFile($this->basePath('vendor/admin-lte/dist/js/app.js'))
        ->appendFile($this->basePath('vendor/notifyjs/dist/notify.js'))
    ?>

</head>
<body class="hold-transition login-page" >
    <?= $this->content ?>
    <?= $this->inlineScript() ?>
</body>
</html>