<? $this->layout()->header = 'Acessos do Salao' ?>
<!-- Main content -->
<section class="content">
    <div class="box box-primary">

        <div class="box-header with-border">
            <a class="btn btn-primary" data-toggle="modal"><i class="fa fa-fw fa-plus-circle"></i>Novo Acesso</a>
        </div>

        <div class="box-body">
            <table class="table table-condensed">
                <tr>
                    <th>Perfil</th>
                    <th>E-mail de Acesso</th>
                    <th></th>
                </tr>
                <tr ng-repeat="acesso in acessos">
                    <td>{{acesso.perfil | perfilToLabel}}</td>
                    <td>{{acesso.email}}</td>
                    <td>
                        <a ng-click="remover(acesso)"><i class="fa fa-fw fa-trash"></i></a>
                    </td>
                </tr>
            </table>
            <div class="fade modal" id="novo-acesso">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title" id="novo-acesso-title">Novo Acesso</h4>
                        </div>
                        <div class="modal-body">
                            <form class="form-horizontal" name="acessoForm">
                                <div class="form-group" ng-hide="acesso.profissionalId">
                                    <div class="col-sm-3">
                                        <label class="control-label">Profissional</label>
                                    </div>
                                    <div class="col-sm-8">
                                        <select class="form-control"  ng-model="profissional.selecionado" ng-options="profissional.id as profissional.nome for profissional in profissionais">
                                            <option value="">Selecione um Profissional</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-3">
                                        <label class="control-label">Perfil</label>
                                    </div>
                                    <div class="col-sm-8">
                                        <select class="form-control" ng-model="acesso.perfil">
                                            <option value="">Selecione um Perfil</option>
                                            <option value="SALAO_ADMIN">Administrador</option>
                                            <option value="SALAO_PROFISSIONAL">Profissional</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-3">
                                        <label class="control-label">E-mail</label>
                                    </div>
                                    <div class="col-sm-8">
                                        <input type="email" class="form-control" placeholder="E-mail de acesso ao sistema" ng-model="acesso.email">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-3">
                                        <label class="control-label">Senha</label>
                                    </div>
                                    <div class="col-sm-8">
                                        <input type="password" class="form-control" placeholder="Senha do usuario" ng-model="acesso.senha">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            <button type="button" class="btn btn-primary" ng-hide="acesso.profissionalId" ng-click="adicionar(profissional.selecionado, acesso)">Salvar</button>
                            <button type="button" class="btn btn-primary" ng-show="acesso.profissionalId" ng-click="atualizar(acesso)">Atualizar</button>

                        </div>
                    </div>
                </div>
            </div>

            <div class="fade modal" id="modal-excluir-acesso">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title" id="myModalLabel">Excluir Acesso</h4>
                        </div>
                        <div class="modal-body">
                            <p>Deseja excluir este acesso ?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                            <button type="button" class="btn btn-primary" ng-click="excluir(acessoConfirm)">Sim</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
