<div class="login-box">
    <div class="login-box-body">
        <p class="login-box-msg">
            Entre com o Login e Senha ou <a href="<?=$this->url('acesso-cadastro')?>" class="text-center">Registre-se</a>
        </p>
        <? /** @var \Acesso\Model\LoginForm $form */ ?>
        <? $form->prepare(); ?>
        <?= $this->form()->openTag($form) ?>
            <div class="form-group has-feedback">
                <?= $this->formInput($form->get('email')) ?>
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <?= $this->formInput($form->get('password')) ?>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <button class="btn btn-primary btn-block btn-flat">Login</button>
                </div>
            </div>
        <?= $this->form()->closeTag($form) ?>
    </div>
</div>