<div class="login-box">
    <div class="login-box-body">
        <p class="login-box-msg">
            Entre com o Login e Senha ou <a href="<?=$this->url('acesso-cadastro')?>" class="text-center">Registre-se</a>
        </p>

        <form name="loginForm">

            <div class="form-group has-feedback">
                <input type="email" name="email" id="email" class="form-control" placeholder="Email" required="required">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="password" id="password" class="form-control" placeholder="Password" required="required" minlength="5" maxlength="10">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <button class="btn btn-primary btn-block btn-flat">Login</button>
                </div>
            </div>
        </form>
    </div>
</div>